name: validation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: make build
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: unit tests, with coverage
        run: make cover
